version: "2"

linters:
  default: none
  enable:
    - logslinter
  settings:
    custom:
      logslinter:
        type: module
        description: Validate literal slog and zap log messages with logsLinter.
        settings:
          rules:
            lowercase-start: true
            english-ascii-only: true
            no-special-chars-or-emoji: true
            no-sensitive-data: true
          sensitive-data:
            additional-keywords:
              - credential
