version: "2"

linters:
  default: none
  enable:
    - logslinter
  settings:
    custom:
      logslinter:
        type: module
        description: Validate literal slog and zap log messages with logsLinter.
