name: Workflow Lint

on:
  push:
    paths:
      - ".github/workflows/**"
      - ".github/actionlint.yaml"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actionlint.yaml"

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: raven-actions/actionlint@v2
